spring:
  application:
    name: config-server
  cloud:
    bus:
      enabled: false
    config:
      server:
        native:
          searchLocations:
           - "file:${user.dir}/src/main/resources/cloud-config"
           - "file:${user.dir}/src/main/resources/cloud-config/{application}"
           - "file:${user.dir}/src/main/resources/cloud-config/{application}-{profile}"
  profiles:
    active: native

server:
  port: 8888
  tomcat:
    accesslog:
      enabled: true
      directory: ${user.dir}/logs
      file-date-format: ".yyyy-MM-dd-HH"
      pattern: '%t|%{User-Agent}i|%m|%U|%q|%s|%B|%D|%{Content-Length}i|%A'
      prefix: access
      rename-on-rotate: false
      suffix: .log
